import os
import tempfile
import matplotlib
matplotlib.use('Agg')  # use non-interactive backend for server environments
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

def generate_radar_chart(metrics, output_path):
    """Generates a score radar chart and saves it as a PNG."""
    labels = ['Composition', 'Color', 'Contrast', 'Aesthetic', 'Balance', 'Symmetry']
    
    # Extract values
    values = [
        metrics.get("composition_score", 0.0),
        metrics.get("color_score", 0.0),
        metrics.get("contrast_score", 0.0),
        metrics.get("aesthetic_score", 0.0),
        metrics.get("balance_score", 0.0),
        metrics.get("symmetry_score", 0.0)
    ]
    
    num_vars = len(labels)
    
    # Compute angles for each axis
    angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
    
    # Complete the circular loop
    values += values[:1]
    angles += angles[:1]
    
    fig, ax = plt.subplots(figsize=(4, 4), subplot_kw=dict(polar=True))
    
    # Draw one axis per variable and add labels
    plt.xticks(angles[:-1], labels, color='#37474F', size=9, weight='bold')
    
    # Draw y-axis labels
    ax.set_rlabel_position(30)
    plt.yticks([20, 40, 60, 80, 100], ["20", "40", "60", "80", "100"], color="#90A4AE", size=7)
    plt.ylim(0, 100)
    
    # Plot and fill data
    ax.plot(angles, values, color='#1E88E5', linewidth=2.5, linestyle='solid')
    ax.fill(angles, values, color='#1E88E5', alpha=0.2)
    
    # Style changes
    ax.spines['polar'].set_color('#CFD8DC')
    ax.grid(True, color='#ECEFF1')
    ax.set_facecolor('#FAFAFA')
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='#FAFAFA')
    plt.close()

def draw_header_footer(canvas, doc):
    """Draws a professional header and footer on later pages."""
    canvas.saveState()
    
    # Header
    canvas.setStrokeColor(colors.HexColor('#1E88E5'))
    canvas.setLineWidth(1)
    canvas.line(54, 738, 558, 738)
    
    canvas.setFont('Helvetica-Bold', 8)
    canvas.setFillColor(colors.HexColor('#37474F'))
    canvas.drawString(54, 744, "ARTCRITIQUE AI — ANALYSIS REPORT")
    
    # Footer
    canvas.setStrokeColor(colors.HexColor('#ECEFF1'))
    canvas.line(54, 54, 558, 54)
    
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#78909C'))
    canvas.drawString(54, 40, "Confidential - Generated by ArtCritique AI Engine")
    canvas.drawRightString(558, 40, f"Page {doc.page}")
    
    canvas.restoreState()

def create_report(filename, results):
    """
    Creates a multi-page PDF analysis report for an artwork.
    
    Parameters:
    - filename: path to write the PDF
    - results: dict returned by database.get_artwork_detail() or constructed during analysis.
    """
    title = results.get("title", "Untitled Artwork")
    created_at = results.get("created_at", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    image_path = results.get("image_path", "")
    metrics = results.get("metrics", {})
    feedback = results.get("feedback", {})

    # Create Radar Chart
    temp_dir = tempfile.gettempdir()
    radar_png_path = os.path.join(temp_dir, f"radar_{datetime.now().strftime('%Y%m%d%H%M%S')}.png")
    generate_radar_chart(metrics, radar_png_path)

    # Styles Setup
    styles = getSampleStyleSheet()
    
    # Custom Palette Styling
    navy = colors.HexColor('#1A237E')
    accent_blue = colors.HexColor('#1E88E5')
    dark_gray = colors.HexColor('#263238')
    light_text = colors.HexColor('#546E7A')
    
    cover_title_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Title'],
        fontName='Helvetica-Bold',
        fontSize=32,
        leading=38,
        textColor=navy,
        alignment=1,
        spaceAfter=15
    )
    
    cover_meta_style = ParagraphStyle(
        'CoverMeta',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        leading=16,
        textColor=light_text,
        alignment=1,
        spaceAfter=25
    )
    
    h1_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=navy,
        spaceBefore=15,
        spaceAfter=12,
        keepWithNext=True
    )

    h2_style = ParagraphStyle(
        'SubHeaderStyle',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=accent_blue,
        spaceBefore=10,
        spaceAfter=8,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=15,
        textColor=dark_gray,
        spaceAfter=10
    )
    
    bullet_style = ParagraphStyle(
        'BulletStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=6
    )

    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=12,
        textColor=colors.white
    )
    
    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=12,
        textColor=dark_gray
    )

    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    story = []

    # ================= PAGE 1: COVER PAGE =================
    story.append(Spacer(1, 40))
    story.append(Paragraph("ArtCritique AI", cover_title_style))
    story.append(Paragraph("Professional Artwork Analysis & Critique Report", ParagraphStyle('CoverSub', parent=cover_title_style, fontSize=16, leading=20, textColor=accent_blue, fontName='Helvetica', spaceAfter=10)))
    story.append(Paragraph(f"<b>Artwork:</b> {title}<br/><b>Date Generated:</b> {created_at}<br/><b>Artist User:</b> Guest Artist", cover_meta_style))
    story.append(Spacer(1, 15))
    
    # Cover Artwork Thumbnail
    if image_path and os.path.exists(image_path):
        # Scale thumbnail maintaining aspect ratio
        from PIL import Image as PILImage
        pil_img = PILImage.open(image_path)
        img_w, img_h = pil_img.size
        max_size = 3.5 * inch # max size on cover
        
        # Calculate aspect ratio scaling
        scale = min(max_size / img_w, max_size / img_h)
        scaled_w = img_w * scale
        scaled_h = img_h * scale
        
        story.append(Image(image_path, width=scaled_w, height=scaled_h))
    
    story.append(Spacer(1, 40))
    story.append(Paragraph("<font color='#1E88E5'><b>Final Skill Classification:</b></font> " + feedback.get("verdict", "Intermediate"), ParagraphStyle('CoverVerdict', parent=cover_meta_style, fontSize=14, leading=18, fontName='Helvetica-Bold')))
    story.append(PageBreak())

    # ================= PAGE 2: DASHBOARD & METRICS =================
    story.append(Paragraph("Aesthetic & Visual Metrics Dashboard", h1_style))
    story.append(Paragraph("Below is a breakdown of low-level visual properties extracted via computer vision combined with high-level aesthetic scores evaluated by the AI critic.", body_style))
    story.append(Spacer(1, 10))

    # Grid layout: Score Table + Radar Chart
    table_data = [
        [Paragraph("Visual Metric", table_header_style), Paragraph("Value / Score", table_header_style)],
        [Paragraph("Composition Score", table_cell_style), Paragraph(f"{metrics.get('composition_score', 0)} / 100", table_cell_style)],
        [Paragraph("Color Harmony Score", table_cell_style), Paragraph(f"{metrics.get('color_score', 0)} / 100", table_cell_style)],
        [Paragraph("Contrast Score", table_cell_style), Paragraph(f"{metrics.get('contrast_score', 0)} / 100", table_cell_style)],
        [Paragraph("Aesthetic Score", table_cell_style), Paragraph(f"{metrics.get('aesthetic_score', 0)} / 100", table_cell_style)],
        [Paragraph("Symmetry Index", table_cell_style), Paragraph(f"{metrics.get('symmetry_score', 0)} %", table_cell_style)],
        [Paragraph("Visual Balance Index", table_cell_style), Paragraph(f"{metrics.get('balance_score', 0)} %", table_cell_style)],
        [Paragraph("Visual Appeal Score (AI)", table_cell_style), Paragraph(f"{feedback.get('visual_appeal_score', 0)} / 100", table_cell_style)],
        [Paragraph("Professional Quality (AI)", table_cell_style), Paragraph(f"{feedback.get('professional_quality_score', 0)} / 100", table_cell_style)]
    ]
    
    # 2.5 inches for metric name, 1.5 inches for score
    score_table = Table(table_data, colWidths=[2.2 * inch, 1.8 * inch])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (1,0), navy),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CFD8DC')),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F5F7F8')])
    ]))

    # Embedding Radar Chart side-by-side or stacked
    # Using Table to align table and radar chart side by side
    radar_flowable = Image(radar_png_path, width=2.8 * inch, height=2.8 * inch)
    
    dashboard_layout = Table([[score_table, radar_flowable]], colWidths=[4.1 * inch, 2.9 * inch])
    dashboard_layout.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (1,0), (1,0), 10),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
    ]))
    
    story.append(dashboard_layout)
    story.append(Spacer(1, 20))
    
    # Style Classification
    story.append(Paragraph("Artistic Style Identification", h2_style))
    style_str = f"<b>Primary Style:</b> {feedback.get('style', 'Unknown')}<br/>"
    confidences = feedback.get("style_percentages", {})
    if confidences:
        style_str += "<b>Style Confidence Breakdown:</b> "
        style_str += ", ".join([f"{k}: {v}%" for k, v in confidences.items() if v > 0])
    story.append(Paragraph(style_str, body_style))
    story.append(PageBreak())

    # ================= PAGE 3: AI CRITIQUE (STRENGTHS/WEAKNESSES) =================
    story.append(Paragraph("AI Core Feedback Critique", h1_style))
    story.append(Paragraph("Actionable critique from the AI engine highlighting strengths, weaknesses, and direct suggestions for immediate enhancement.", body_style))
    story.append(Spacer(1, 10))

    story.append(Paragraph("✦ Strengths", h2_style))
    for s in feedback.get("strengths", []):
        story.append(Paragraph(f"• {s}", bullet_style))
        
    story.append(Spacer(1, 10))
    story.append(Paragraph("✦ Areas for Improvement (Weaknesses)", h2_style))
    for w in feedback.get("weaknesses", []):
        story.append(Paragraph(f"• {w}", bullet_style))
        
    story.append(Spacer(1, 10))
    story.append(Paragraph("✦ Actionable Suggestions", h2_style))
    for sug in feedback.get("suggestions", []):
        story.append(Paragraph(f"• {sug}", bullet_style))
    
    story.append(PageBreak())

    # ================= PAGE 4: DETAILED INSIGHTS & ROADMAP =================
    story.append(Paragraph("Professional Insights & Roadmap", h1_style))
    
    story.append(Paragraph("✦ Detailed Review & Analysis", h2_style))
    insights_text = feedback.get("insights", "No details available.")
    # Replace newlines with Paragraph breaks
    for paragraph in insights_text.split('\n\n'):
        if paragraph.strip():
            story.append(Paragraph(paragraph.strip(), body_style))
            
    story.append(Spacer(1, 10))
    story.append(Paragraph("✦ Skill Improvement Roadmap", h2_style))
    
    story.append(Paragraph("<b>Immediate / Tactical Fixes:</b>", body_style))
    for fix in feedback.get("roadmap_immediate", []):
        story.append(Paragraph(f"• {fix}", bullet_style))
        
    story.append(Spacer(1, 5))
    story.append(Paragraph("<b>Long-Term Skill Development:</b>", body_style))
    for item in feedback.get("roadmap_longterm", []):
        story.append(Paragraph(f"• {item}", bullet_style))

    # Build PDF doc
    doc.build(
        story,
        onFirstPage=lambda canv, doc: None,  # No headers/footers on cover
        onLaterPages=draw_header_footer
    )

    # Clean up radar png
    try:
        if os.path.exists(radar_png_path):
            os.remove(radar_png_path)
    except Exception:
        pass