import sqlite3
from modules.database import get_db_connection

def init_auth_db():
    """
    Migrates the SQLite database to ensure the users table contains 
    a password_hash column. Runs at Streamlit application startup.
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        # Check if password_hash column is present in the users table
        cursor.execute("SELECT password_hash FROM users LIMIT 1")
    except sqlite3.OperationalError:
        # Column does not exist, alter table to append it
        cursor.execute("ALTER TABLE users ADD COLUMN password_hash TEXT")
        conn.commit()
        print("Database Migration: Successfully added password_hash to users table.")
    finally:
        conn.close()

def get_user_by_email(email):
    """
    Retrieves user profile details (ID, name, email, and password hash) 
    by their registered email address. Returns None if email is not found.
    
    Parameters:
    - email: str, email address to look up
    
    Returns:
    - user: dict or None
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "SELECT id, name, email, password_hash FROM users WHERE LOWER(email) = ?",
            (email.strip().lower(),)
        )
        row = cursor.fetchone()
        if row:
            return dict(row)
        return None
    finally:
        conn.close()

def create_user(name, email, password_hash):
    """
    Creates a new user record in the SQLite database.
    
    Parameters:
    - name: str, user's full name
    - email: str, user's unique email address
    - password_hash: str, hashed password string
    
    Returns:
    - user_id: int, the autogenerated primary key of the new user
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "INSERT INTO users (name, email, password_hash) VALUES (?, ?, ?)",
            (name.strip(), email.strip().lower(), password_hash)
        )
        conn.commit()
        return cursor.lastrowid
    except Exception as e:
        conn.rollback()
        raise e
    finally:
        conn.close()

def update_user_password(email, new_password_hash):
    """
    Updates the password hash for a registered email address.
    Used during password recovery and resets.
    
    Parameters:
    - email: str, user's email address
    - new_password_hash: str, new hashed password string
    """
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "UPDATE users SET password_hash = ? WHERE LOWER(email) = ?",
            (new_password_hash, email.strip().lower())
        )
        conn.commit()
    except Exception as e:
        conn.rollback()
        raise e
    finally:
        conn.close()
